# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f9d5988f2f846fecc4681c383c14d1f26aa941ca42a46b91b0b3e8a208ed0ca6a4a5aa67eba5573ae01819acccadfe96d6ea6e701c3ee4744edc3383cfb5230

test:
  secret_key_base: ed144cd34cd816799f96896893a96bb9453248a6a7c24536f88e04f51a5254530d50fa771816ec73839e895451e81b94fc225750f6a185b4826385367cfe30c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
